# Configuration file for Webserver

server {
    host 127.0.0.1;
    port 8081;

    # Default server for this host:port
    server_name localhost;

    # Default error pages
    error_page 404 /errors/404.html;
    error_page 500 /errors/500.html;

    # Max client body size (e.g., for uploads)
    client_max_body_size 10M;

    location / {
        methods GET POST DELETE;
        root ./webpage;
        index pages/Home/Home.html;
        autoindex off;
    }

    location /upload 	{
        methods POST;
        root ./webpage/uploads;
        upload_enable on;
        upload_store ./webpage/uploads;
    }

    location /cgi-bin {
        methods GET POST;
        root ./webpage/cgi-bin/;
        cgi_extension .cgi;
        cgi_path /usr/bin/python3;
    }

    location /redirect-me {
        redirect http://example.com;
    }
    
    location *.bar {
        methods GET;
        root ./var/www/files;
        autoindex on;
    }

    location /pages {
        methods GET;
        root ./webpage/pages;
        autoindex on;
    }
        location /directory {
        methods GET;
        root ./YoupiBanane;
        index youpi.bad_extension;
    }
}

server {
    host 127.0.0.1;
    port 8081;

    # No server_name = will match by default if host:port matches

    location / {
        methods GET;
        root /var/www/alternative;
        index home.html;
        autoindex off;
    }
}