# Configuration file for Webserv

server {
    host 127.0.0.1;
    port 8001;

    # Default server for this host:port
    server_name localhost;

    client_body_temp_path ./YoupiBanane/;

    # Default error pages
    error_page 404 /errors/404.html;
    error_page 500 /errors/500.html;

    # Max client body size (e.g., for uploads)
    client_max_body_size 140000000;

    location / {
        methods GET;
        root ./YoupiBanane;
        index ./youpi.bad_extension;
        autoindex off;
    }

    location /post_body {
        methods POST;
        client_max_body_size 100;
    }

    location /directory {
        methods GET;
        root ./YoupiBanane;
        index ./youpi.bad_extension;
    }

    location *.bla {
        methods POST;
        cgi_pass ./webpage/cgi-bin/ubuntu_cgi_tester;
    }
}

server {
    host 127.0.0.1;
    port 8081;

    # No server_name = will match by default if host:port matches

    location / {
        methods GET;
        root ./var/www/html/;
        index login.html;
        autoindex off;
    }
}
    